### ISSUE TITLE
Relicense to a liberal license

### ISSUE THREAD

**Issue by davidfetter** [levkk/pgcat#15]
MIT is generally pretty uncontroversial, and to my knowledge never gets attorneys involved.

If you think any form of the GPL will actually "protect" your work from people using it for proprietary purposes and get you paid when they do, you have not been paying attention.

**Comment by levkk** [comment]
GPL allows private use. While it may make some people think about if they can use this or not, GPL software is commonly used in companies, e.g. the Linux kernel would be a good example.

I don't think it's fair for you to assume my intentions.
