### ISSUE TITLE
Timestamped logs

### ISSUE THREAD

**Issue by zainkabani** [levkk/pgcat#153]
**Is your feature request related to a problem? Please describe.**

The current logger gives timestamps by second which makes it hard to understand the order of events since events are so frequent

**Describe the solution you'd like**

Would like logs to be timestamped my millisecond.

**Describe alternatives you've considered**

It would be great if we could get millisecond precision in the logs using something like [env_logger](https://docs.rs/env_logger/latest/env_logger/index.html)

**Additional context**

**Comment by levkk** [comment]
[This](https://docs.rs/env_logger/latest/env_logger/struct.Builder.html#method.format_timestamp_nanos) looks like the solution.

**Comment by levkk** [comment]
#156
