### ISSUE TITLE
pause/resume commands supports

### ISSUE THREAD

**Issue by jurim76** [levkk/pgcat#177]
The killer feature of pgbouncer is pause/resume commands to restart postgres seamlessly for clients. There are similar [issue](https://github.com/yandex/odyssey/issues/32) and [PR](https://github.com/yandex/odyssey/pull/87) for odyssey, but seems to be abandoned.
It would be nice to implement these commands in pgcat.

**Comment by levkk** [comment]
Done :)

**Comment by jurim76** [comment]
Amazing! :)
