### ISSUE TITLE
The example provided is not working

### ISSUE THREAD

**Issue by Sarna555** [levkk/pgcat#192]
**Describe the bug**
Example usage isn't working (at least not out of the box).

**To Reproduce**
```
docker-compose up
psql -U postgres -h 127.0.0.1 -p 6432 -d postgres
Password for user postgres:
psql: error: connection to server at "127.0.0.1", port 6432 failed: FATAL:  No pool configured for database: "postgres", user: "postgres"
```

**Expected behavior**
Working out of the box

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Comment by mismaah** [comment]
Did you manage to get it working? If so, how? I'm having the same issue.
