### ISSUE TITLE
Dockerhub docker image is 9 months old

### ISSUE THREAD

**Issue by AeroNotix** [levkk/pgcat#227]
Just as a _guess_, ... there is a newer version available.

Is Dockerhub the main repo that is used for this project?

**Comment by levkk** [comment]
Good question, I haven't updated that one in a while. Building your own should be really simple though:

```bash
docker build .
```

from the root of the repo.

When I get a moment, I'll update the the Docker hub image. The project doesn't follow semver (yet), so I don't expect to keep that image up-to-date for the time being.

**Comment by AeroNotix** [comment]
I did build my own.
