### ISSUE TITLE
When dbname is not specified, pgcat responds with error

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [levkk/pgcat#231]
**Describe the bug**
I am trying to use a rust postgres project which uses r2d2.
When the connection url does not include dbname, pgcat responds with ClientError.
The behaviour should be that the username is taken and used as database.

I am testing this with YugabyteDB, where the default database is yugabyte, not postgres.
We are 100% wire compatible and use the postgres source for the database.

**Expected behavior**
The behaviour should be that the username is taken and used as database.

**Desktop (please complete the following information):**
 - OS: Mac OSX 12.6

**Comment by fritshoogland-yugabyte** [comment]
Second remark concerning this bug: if an error is returned, be as clear as possible what is the issue, such as the missing dbname/ database specification here.

**Comment by levkk** [comment]
Nice find. Should be an easy fix: https://github.com/levkk/pgcat/blob/main/src/client.rs#L363

A PR is welcome if you'd like to contribute; otherwise I can fix this later this week.
