### ISSUE TITLE
Relicense to AGPL?

### ISSUE THREAD

**Issue by tasn** [levkk/pgcat#3]
Hey, super cool project!

I'm not advocating for or against either license, it's just that the GPL probably doesn't do what you want. The GPL essentially has no effect for software that's meant to be used over the internet. It only applies to distributing binaries.

AGPL on the other hand, was written with this in mind.

**Comment by niltooth** [comment]
AGPL is banned in a lot of large corporations.

**Comment by tasn** [comment]
I'm not advocating AGPL, I just wanted to point out that GPL doesn't add a lot of protection to such a project (and AGPL does), and I just wanted to make sure you're aware of that.
