### ISSUE TITLE
Continous Push to a Public Image Registry e.g. Docker Hub or Github Image Registry

### ISSUE THREAD

**Issue by sherifkayad** [levkk/pgcat#367]
**Is your feature request related to a problem? Please describe.**
The project doesn't seem to be pushing the image continously to the Docker Hub.

**Describe the solution you'd like**
I know it's fairly simply to build your own image, however, what would be best is to have an official image being pushed to a public image registry e.g. the Docker Hub or to Github Image Registry, .. etc.

**Describe alternatives you've considered**
Building your own image, however, that will come at the cost of having to maintain a separate project to keep up with the updates here.

**Additional context**
Nothing further.

**Comment by Fraser-Isbester** [comment]
@levkk how do you feel about us setting this up in GHCR via GH actions?

**Comment by levkk** [comment]
Sounds good to me!
