### ISSUE TITLE
selected wrong shard and the connection keep reporting fatal

### ISSUE THREAD

**Issue by DeoLeung** [levkk/pgcat#80]
**Describe the bug**
selected wrong shard and the connection keep reporting fatal

**To Reproduce**
* create 2 shards, naming shard 0 and 1
* in a db ide, open a session
* `SET shard TO '2';`, it reports FATAL:  shard 2 is more than configured 2
* `SET shard TO '0';`, it reports FATAL:  shard 2 is more than configured 2

**Expected behavior**
be able to set shard to 0 and 1 after setting a wrong one

**Comment by levkk** [comment]
Thanks for reporting. Could you provide a full example in SQL that I can run on my end? I'm unable to reproduce the bug currently with the above instructions.

**Comment by DeoLeung** [comment]
hmmm...I can't reproduce it either...I think it may partially relate to #81 

* restart pgcat
* open my postico ide
* type `SET SHARD TO '2';` , it's now reporting `ERROR:  unrecognized configuration parameter "shard"` even if i capitalize them.
* and I'm using the config from circleci with only user and shards modified

![image](https://user-images.githubusercontent.com/3764720/174962614-21c1a649-09c0-41b5-a7ce-d529cb16d5b9.png)

**Comment by DeoLeung** [comment]
seems no config for that, I'll report to postico then :)

**Comment by levkk** [comment]
I found the bug you originally saw I think and fixing it in #84 . It's subtle, so very good find, thank you!
