### ISSUE TITLE
support exporting metrics like pgbouncer

### ISSUE THREAD

**Issue by DeoLeung** [levkk/pgcat#83]
**Is your feature request related to a problem? Please describe.**
we are using `spreaker/prometheus-pgbouncer-exporter` to monitor our pgbouncers, it will be great if pgcat has compatible metrics

**Describe the solution you'd like**
could be scrape by prometheus exporters, typically existing `pgbouncer` exporters

**Describe alternatives you've considered**
use general postgres exporter and manually craft the stat sql

**Comment by chhetripradeep** [comment]
Can i pick this issue and add a prometheus compatible metrics endpoint.

**Comment by levkk** [comment]
I'm not too familiar with how Prometheus does this. Is this more than having an admin database with commands that can show the stats?

Currently, PgCat supports a decent amount of statistics like `SHOW POOLS`, `SHOW STATS`, `SHOW LISTS`, etc. I used Datadog as my reference for implementing the admin queries at the time, so if Prometheus needs more (I believe PgBouncer supports a few more as well), I think that's a good idea.

```sql
psql -d pgcat -c 'SHOW STATS'
psql -d pgbouncer -c 'SHOW STATS'
psql -d pgbouncer -c 'SHOW POOLS'
```

**Comment by danielhoherd** [comment]
@levkk the way prometheus gets its metrics is by periodically scraping an HTTP endpoint that has the metrics listed in a specific format. If you click in to this demo instance <https://prometheus.demo.do.prometheus.io/targets> and click on one of the endpoints you'll see how the data is exposed. Sometimes this data is exposed by the process that is serving the service that is being monitored, and sometimes the data is exposed by a secondary service, usually called `<servicename>-exporter`, eg: <https://github.com/prometheus-community/pgbouncer_exporter>. It seems like what you are talking about with the `psql` commands in the prior comment, this might be possible to do as a secondary service.

**Comment by dat2** [comment]
@chhetripradeep @levkk I've created a PR for this in https://github.com/levkk/pgcat/pull/107. Feel free to review and leave any comments!

**Comment by levkk** [comment]
Thank you very much for your contribution. Welcome to the project!
