### ISSUE TITLE
Query router doc confusion

### ISSUE THREAD

**Issue by wenq1** [levkk/pgcat#92]
Doc says
```
-- To talk to the primary for the duration of the next transaction:
SET SERVER ROLE TO 'primary';
```

And says
```
The setting will persist until it's changed again or the client disconnects.
```

If I set server role to 'primary', will it just affect the next transaction/statement or will it affect the entire session? The doc seems self contradictory.

Also, wouldn't it be sounding more natural to rework the semantics of this this custom query to:

```
SET SERVER TARGET TO 'primary'
```

**Comment by levkk** [comment]
> The setting will persist until it's changed again or the client disconnects.

This setting will stay the same, i.e. `primary` until it's changed again with `SET SERVER ROLE TO` or the client disconnects and re-connects. All settings set using this custom SQL syntax are local to each connected client and are not shared.

Using your definition, the setting will affect the entire session.
